# Application-level constants and configuration for Spring Boot
spring:
  application:
    name: dev-commute
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://ride_sharing_postgres:5432/ride_sharing
    username: ride_user
    password: ride_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Keep kafka config as-is

kafka:
  topic:
    orders: orders
    rides: rides
    partitions: 10
  headers:
    messageType: messageType
    user: user

logging:
  level:
    root: WARN          
    com.example.kafka: INFO