name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: dockertag
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "master" ]]; then
            git fetch --tags
            latest_tag=$(git tag --list '1.0.*' --sort=-v:refname | head -n 1)
            if [ -z "$latest_tag" ]; then
              new_tag="1.0.0"
            else
              IFS='.' read -r major minor patch <<<"${latest_tag//v/}"
              patch=$((patch + 1))
              new_tag="$major.$minor.$patch"
            fi
            echo "New version tag: $new_tag"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag $new_tag
            git push origin $new_tag
            echo "tag=$new_tag" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./dev-commute
          file: ./dev-commute/Dockerfile
          push: true
          tags: |
            abnaveshubham/dev-commute:${{ steps.dockertag.outputs.tag }}
            abnaveshubham/dev-commute:latest
